import type { Metadata } from 'next';
import './globals.css';
import { Provider } from '@/components/ui/provider';

export const metadata: Metadata = {
  title: 'My language teacher',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="light">
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
